In [1]:
# ==========================================
# 📦 IMPORTS
# ==========================================
import pandas as pd
import numpy as np
import kagglehub
import re
import os

In [2]:
# Cargando el dataset

path = kagglehub.dataset_download("wafaaelhusseini/extended-recipes-dataset-64k-dishes")
print("Path:", path)
df = pd.read_csv(os.path.join(path, "recipes_extended.csv"))
print("Dataset cargado correctamente\n")

Downloading to /home/ramon/.cache/kagglehub/datasets/wafaaelhusseini/extended-recipes-dataset-64k-dishes/1.archive...

100%|██████████| 78.3M/78.3M [00:02<00:00, 37.7MB/s]

Extracting files...

Path: /home/ramon/.cache/kagglehub/datasets/wafaaelhusseini/extended-recipes-dataset-64k-dishes/versions/1
Dataset cargado correctamente

In [3]:
df.head()

,recipe_title,category,subcategory,description,ingredients,directions,num_ingredients,num_steps,ingredient_text,directions_text,...,is_halal,is_kosher,is_nut_free,is_dairy_free,is_gluten_free,dietary_profile,healthiness_score,health_flags,main_ingredient,health_level
0,Air Fryer Potato Slices with Dipping Sauce,Air Fryer Recipes,Air Fryer Recipes,"These air fryer potato slices, served with a b...","[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...","[""Combine ketchup, beer, Worcestershire sauce,...",9,5,ketchup beer worcestershire sauce onion powder...,"combine ketchup, beer, worcestershire sauce, o...",...,False,True,True,True,True,"[""vegan"", ""gluten_free"", ""nut_free"", ""kosher""]",80,"[""plant_based"", ""healthy_fats"", ""fried""]",unknown,healthy
1,Gochujang Pork Belly Bites,Air Fryer Recipes,Air Fryer Recipes,These gochujang pork belly bites are sweet and...,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...","[""Preheat an air fryer to 400 degrees F (200 d...",5,4,pound pork belly gochujang soy sauce honey gro...,preheat an air fryer to 400 degrees f (200 deg...,...,False,False,True,True,True,"[""gluten_free"", ""nut_free""]",64,"[""sugary""]",red_meat,moderate
2,3-Ingredient Air Fryer Everything Bagel Chicke...,Air Fryer Recipes,Air Fryer Recipes,These 3-ingredient air fryer everything bagel ...,"[""1 ¼ pounds chicken tenders"", ""1 tablespoon o...","[""Gather all ingredients. Preheat an air fryer...",3,4,¼ pounds chicken tenders olive oil everything ...,gather all ingredients. preheat an air fryer t...,...,True,True,True,True,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",68,"[""healthy_fats"", ""fried""]",poultry,moderate
3,Air Fryer Everything Bagel Chicken Cutlets,Air Fryer Recipes,Air Fryer Recipes,These air fryer everything bagel chicken cutle...,"[""4 chicken cutlets (about 1 pound total)"", ""s...","[""Preheat an air fryer to 400 degrees F (200 d...",9,9,chicken cutlets about pound total salt freshly...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,False,False,"[""nut_free"", ""halal"", ""kosher""]",70,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",poultry,moderate
4,Air Fryer Honey Sriracha Salmon Bites,Air Fryer Recipes,Air Fryer Recipes,These air fryer honey Sriracha salmon bites ar...,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...","[""Preheat an air fryer to 400 degrees F (200 d...",5,5,soy sauce honey sriracha rice vinegar granulat...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,True,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",74,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",unknown,moderate

In [4]:



# ==========================================
# 🔍 EXPLORACIÓN INICIAL
# ==========================================
print("Shape:", df.shape)
print("\nColumnas:\n", df.columns)

print("\nTipos de datos:\n", df.dtypes)

print("\nValores nulos:\n")
print(df.isnull().sum())

Shape: (62126, 38)

Columnas:
 Index(['recipe_title', 'category', 'subcategory', 'description', 'ingredients',
       'directions', 'num_ingredients', 'num_steps', 'ingredient_text',
       'directions_text', 'combined_text', 'ingredients_raw', 'directions_raw',
       'ingredients_canonical', 'cuisine_list', 'course_list', 'tastes',
       'primary_taste', 'secondary_taste', 'fast_hits', 'slow_hits',
       'medium_hits', 'cook_speed', 'est_prep_time_min', 'est_cook_time_min',
       'difficulty', 'is_vegan', 'is_vegetarian', 'is_halal', 'is_kosher',
       'is_nut_free', 'is_dairy_free', 'is_gluten_free', 'dietary_profile',
       'healthiness_score', 'health_flags', 'main_ingredient', 'health_level'],
      dtype='str')

Tipos de datos:
 recipe_title               str
category                   str
subcategory                str
description                str
ingredients                str
directions                 str
num_ingredients          int64
num_steps                int64
ingredient_text            str
directions_text            str
combined_text              str
ingredients_raw            str
directions_raw             str
ingredients_canonical      str
cuisine_list               str
course_list                str
tastes                     str
primary_taste              str
secondary_taste            str
fast_hits                int64
slow_hits                int64
medium_hits              int64
cook_speed                 str
est_prep_time_min        int64
est_cook_time_min        int64
difficulty                 str
is_vegan                  bool
is_vegetarian             bool
is_halal                  bool
is_kosher                 bool
is_nut_free               bool
is_dairy_free             bool
is_gluten_free            bool
dietary_profile            str
healthiness_score        int64
health_flags               str
main_ingredient            str
health_level               str
dtype: object

Valores nulos:

recipe_title             0
category                 0
subcategory              0
description              0
ingredients              0
directions               0
num_ingredients          0
num_steps                0
ingredient_text          0
directions_text          0
combined_text            0
ingredients_raw          0
directions_raw           0
ingredients_canonical    0
cuisine_list             0
course_list              0
tastes                   0
primary_taste            0
secondary_taste          0
fast_hits                0
slow_hits                0
medium_hits              0
cook_speed               0
est_prep_time_min        0
est_cook_time_min        0
difficulty               0
is_vegan                 0
is_vegetarian            0
is_halal                 0
is_kosher                0
is_nut_free              0
is_dairy_free            0
is_gluten_free           0
dietary_profile          0
healthiness_score        0
health_flags             0
main_ingredient          0
health_level             0
dtype: int64

In [5]:
print("Total de categorías:", df["category"].nunique())
print(df["category"].unique())

Total de categorías: 267
<StringArray>
[         'Air Fryer Recipes', 'Allrecipes Allstar Recipes',
           'Angel Food Cakes',                  'Antipasti',
      'Appetizers And Snacks',                  'Apple Pie',
                 'Applesauce',             'Artichoke Dips',
                     'Bagels',                'Baked Beans',
 ...
                    'Waffles',             'Waldorf Salads',
         'Whole Wheat Breads',                    'Whole30',
               'Whoopie Pies',              'Winter Squash',
                       'Yams',               'Yeast Breads',
                       'Ziti',            'Zucchini Breads']
Length: 267, dtype: str

In [6]:
print("Total de subcategorías:", df["subcategory"].nunique())
print(df["subcategory"].unique())

Total de subcategorías: 1032
<StringArray>
[                       'Air Fryer Recipes',
              'Air Fryer Main Dish Recipes',
              'Air Fryer Side Dish Recipes',
    'Air Fryer Appetizer And Snack Recipes',
               'Allrecipes Allstar Recipes',
           'Allrecipes Allstars Appetizers',
                'Allrecipes Allstars Bread',
 'Allrecipes Allstars Breakfast And Brunch',
             'Allrecipes Allstars Desserts',
               'Allrecipes Allstars Drinks',
 ...
                 'Butternut Squash Recipes',
                 'Spaghetti Squash Recipes',
                  'Delicata Squash Recipes',
                     'Bitter Melon Recipes',
                     'Acorn Squash Recipes',
                                     'Yams',
                             'Yeast Breads',
                                'Rye Bread',
                                     'Ziti',
                          'Zucchini Breads']
Length: 1032, dtype: str

In [7]:
print("Total de dietary profiles", df["dietary_profile"].nunique())
print(df["dietary_profile"].unique())

Total de dietary profiles 31
<StringArray>
[         '["vegan", "gluten_free", "nut_free", "kosher"]',
                             '["gluten_free", "nut_free"]',
          '["gluten_free", "nut_free", "halal", "kosher"]',
                         '["nut_free", "halal", "kosher"]',
                      '["gluten_free", "halal", "kosher"]',
                '["vegan", "nut_free", "halal", "kosher"]',
 '["vegan", "gluten_free", "nut_free", "halal", "kosher"]',
                   '["gluten_free", "nut_free", "kosher"]',
                                  '["nut_free", "kosher"]',
                                   '["nut_free", "halal"]',
                                            '["nut_free"]',
                                     '["halal", "kosher"]',
                    '["gluten_free", "nut_free", "halal"]',
             '["vegan", "gluten_free", "halal", "kosher"]',
           '["vegan", "gluten_free", "nut_free", "halal"]',
                                              '["kosher"]',
                                         '["unspecified"]',
                    '["vegan", "gluten_free", "nut_free"]',
                                         '["gluten_free"]',
                               '["gluten_free", "kosher"]',
                            '["vegan", "halal", "kosher"]',
                                     '["vegan", "kosher"]',
                         '["vegan", "nut_free", "kosher"]',
                                               '["halal"]',
                                '["gluten_free", "halal"]',
                                   '["vegan", "nut_free"]',
                      '["vegan", "gluten_free", "kosher"]',
                                '["vegan", "gluten_free"]',
                       '["vegan", "gluten_free", "halal"]',
                          '["vegan", "nut_free", "halal"]',
                                               '["vegan"]']
Length: 31, dtype: str

In [8]:
import json

# Convertir strings JSON a listas reales
listas = df["dietary_profile"].apply(json.loads)
# Obtener todos los valores únicos
valores_unicos = set()

for lista in listas:
    valores_unicos.update(lista)

print(valores_unicos)

{'halal', 'nut_free', 'vegan', 'gluten_free', 'kosher', 'unspecified'}

Yo esperaba los 7 valores más el unespecified
is_vegan                   bool
is_vegetarian              bool
is_halal                   bool
is_kosher                  bool
is_nut_free                bool
is_dairy_free              bool
is_gluten_free             bool

Vamos a buscar si alguno tiene vegetarian

In [9]:
# alguno tendrá vegetarian como true?
print(df["is_vegetarian"].sum())
df[df["is_vegetarian"]]

41632

,recipe_title,category,subcategory,description,ingredients,directions,num_ingredients,num_steps,ingredient_text,directions_text,...,is_halal,is_kosher,is_nut_free,is_dairy_free,is_gluten_free,dietary_profile,healthiness_score,health_flags,main_ingredient,health_level
0,Air Fryer Potato Slices with Dipping Sauce,Air Fryer Recipes,Air Fryer Recipes,"These air fryer potato slices, served with a b...","[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...","[""Combine ketchup, beer, Worcestershire sauce,...",9,5,ketchup beer worcestershire sauce onion powder...,"combine ketchup, beer, worcestershire sauce, o...",...,False,True,True,True,True,"[""vegan"", ""gluten_free"", ""nut_free"", ""kosher""]",80,"[""plant_based"", ""healthy_fats"", ""fried""]",unknown,healthy
4,Air Fryer Honey Sriracha Salmon Bites,Air Fryer Recipes,Air Fryer Recipes,These air fryer honey Sriracha salmon bites ar...,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...","[""Preheat an air fryer to 400 degrees F (200 d...",5,5,soy sauce honey sriracha rice vinegar granulat...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,True,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",74,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",unknown,moderate
5,Air Fryer Corn on The Cob,Air Fryer Recipes,Air Fryer Recipes,Air fryer corn on the cob is super quick to ma...,"[""¼ cup mayonnaise"", ""2 teaspoons crumbled cot...","[""Preheat an air fryer to 400 degrees F (200 d...",6,4,¼ mayonnaise crumbled cotija cheese lime juice...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,False,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",70,"[""neutral""]",egg_dairy,moderate
7,Air Fryer Crispy Onions,Air Fryer Recipes,Air Fryer Recipes,These air fryer crispy onions are delicious ov...,"[""1/4 cup all-purpose flour"", ""1/2 teaspoon ca...","[""Preheat an air fryer to 375 degrees F (190 d...",5,3,all-purpose flour cayenne pepper salt taste on...,preheat an air fryer to 375 degrees f (190 deg...,...,True,True,True,True,False,"[""vegan"", ""nut_free"", ""halal"", ""kosher""]",80,"[""plant_based"", ""healthy_fats"", ""fried""]",unknown,healthy
8,Air Fryer Hot Honey Glazed Carrots,Air Fryer Recipes,Air Fryer Recipes,These air fryer hot honey glazed carrots are a...,"[""nonstick cooking spray"", ""2 tablespoons butt...","[""Preheat an air fryer to 400 degrees F (200 d...",4,3,nonstick cooking spray butter hot honey such a...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,False,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",62,"[""plant_based"", ""sugary"", ""fried""]",unknown,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62121,Rice Zucchini Muffins,Zucchini Breads,Zucchini Muffins,I created this for my son who has many food al...,"[""1 cup rice flour"", ""1 cup cooked rice"", ""¾ c...","[""Preheat oven to 350 degrees F (175 degrees C...",11,3,rice flour cooked rice ¾ white sugar ½ applesa...,preheat oven to 350 degrees f (175 degrees c)....,...,True,True,True,True,False,"[""vegan"", ""nut_free"", ""halal"", ""kosher""]",60,"[""plant_based"", ""sugary"", ""fried""]",unknown,moderate
62122,Gluten-Free Zucchini Muffins,Zucchini Breads,Zucchini Muffins,These gluten-free muffins are so good you won'...,"[""cooking spray"", ""1 cup vanilla whey protein ...","[""Preheat the oven to 350 degrees F (175 degre...",15,5,cooking spray vanilla whey protein powder ⅓ ta...,preheat the oven to 350 degrees f (175 degrees...,...,True,True,True,False,False,"[""vegan"", ""nut_free"", ""halal"", ""kosher""]",80,"[""plant_based"", ""healthy_fats"", ""fried""]",egg_dairy,healthy
62123,Five Spice Muffins,Zucchini Breads,Zucchini Muffins,These muffins are versatile and always moist a...,"[""2 cups shredded zucchini"", ""⅓ cup boiling wa...","[""Preheat oven to 350 degrees F (175 degrees C...",14,5,shredded zucchini ⅓ boiling water ¾ all-purpos...,preheat oven to 350 degrees f (175 degrees c)....,...,True,True,False,True,False,"[""vegan"", ""halal"", ""kosher""]",56,"[""plant_based"", ""sugary"", ""fried""]",egg_dairy,moderate
62124,Low-Fat Chocolate Zucchini Mini Muffins,Zucchini Breads,Zucchini Muffins,A sweet snack your kids will gobble up and you...,"[""cooking spray"", ""2 (1 ounce) squares unsweet...","[""Preheat oven to 350 degrees F (175 degrees C...",14,5,cooking spray ounce squares unsweetened chocol...,preheat oven to 350 degrees f (175 degrees c)....,...,True,True,True,True,False,"[""nut_free"", ""halal"", ""kosher""]",64,"[""plant_based"", ""whole_grains"", ""sugary""]",egg_dairy,moderate
62125,Vegan Zucchini Bread Muffins,Zucchini Breads,Zucchini Muffins,Modified an old recipe and cut 1/2 the sugar a...,"[""½ cup warm water"", ""6 tablespoons flax seed ...","[""Preheat oven to 350 degrees F (175 degrees C...",15,5,½ warm water flax seed meal turbinado sugar ¾ ...,preheat oven to 350 degrees f (175 degrees c)....,...,True,True,False,True,False,"[""vegan"", ""halal"", ""kosher""]",58,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",unknown,moderate

In [10]:
# saber si el dietary profile tiene vegetarian o no
df[df["dietary_profile"].str.contains("vegetarian", na=False)]

Empty DataFrame
Columns: [recipe_title, category, subcategory, description, ingredients, directions, num_ingredients, num_steps, ingredient_text, directions_text, combined_text, ingredients_raw, directions_raw, ingredients_canonical, cuisine_list, course_list, tastes, primary_taste, secondary_taste, fast_hits, slow_hits, medium_hits, cook_speed, est_prep_time_min, est_cook_time_min, difficulty, is_vegan, is_vegetarian, is_halal, is_kosher, is_nut_free, is_dairy_free, is_gluten_free, dietary_profile, healthiness_score, health_flags, main_ingredient, health_level]
Index: []

[0 rows x 38 columns]

In [11]:
# ninguno lo tiene aunque la columna de is_vegetarian si tiene valores
# yo creo que podemos cambiar eso
# pero antes de eso vamos a hacer lo mismo para dairy free
# alguno tendrá vegetarian como true?
print(df["is_dairy_free"].sum())
df[df["is_dairy_free"]]

# hay que validar tmb que el dietary profile no lo tiene
df[df["dietary_profile"].str.contains("dairy", na=False)]

23731

Empty DataFrame
Columns: [recipe_title, category, subcategory, description, ingredients, directions, num_ingredients, num_steps, ingredient_text, directions_text, combined_text, ingredients_raw, directions_raw, ingredients_canonical, cuisine_list, course_list, tastes, primary_taste, secondary_taste, fast_hits, slow_hits, medium_hits, cook_speed, est_prep_time_min, est_cook_time_min, difficulty, is_vegan, is_vegetarian, is_halal, is_kosher, is_nut_free, is_dairy_free, is_gluten_free, dietary_profile, healthiness_score, health_flags, main_ingredient, health_level]
Index: []

[0 rows x 38 columns]

In [ ]:
# tmb hay que modificar esos valores, creo que podemos hacerlo para los dos

In [12]:
# por que algunos tienen unespecified si tiene algunos otros TRUE?

df[
    (df["dietary_profile"].str.contains("unspecified", na=False)) & (
        (df["is_vegan"] == True) |
        (df["is_vegetarian"] == True) |
        (df["is_halal"] == True) |
        (df["is_kosher"] == True) |
        (df["is_nut_free"] == True) |
        (df["is_dairy_free"] == True) |
        (df["is_gluten_free"] == True)
    )
][[
    "dietary_profile",
    "is_vegan",
    "is_vegetarian",
    "is_halal",
    "is_kosher",
    "is_nut_free",
    "is_dairy_free",
    "is_gluten_free"
]].head(20)

,dietary_profile,is_vegan,is_vegetarian,is_halal,is_kosher,is_nut_free,is_dairy_free,is_gluten_free
688,"[""unspecified""]",False,True,False,False,False,False,False
1588,"[""unspecified""]",False,False,False,False,False,True,False
1673,"[""unspecified""]",False,False,False,False,False,True,False
7286,"[""unspecified""]",False,True,False,False,False,False,False
8298,"[""unspecified""]",False,True,False,False,False,False,False
8481,"[""unspecified""]",False,True,False,False,False,False,False
9748,"[""unspecified""]",False,False,False,False,False,True,False
12939,"[""unspecified""]",False,True,False,False,False,False,False
20443,"[""unspecified""]",False,False,False,False,False,True,False
23273,"[""unspecified""]",False,True,False,False,False,False,False
26563,"[""unspecified""]",False,True,False,False,False,False,False
27627,"[""unspecified""]",False,True,False,False,False,False,False
28278,"[""unspecified""]",False,False,False,False,False,True,False
30041,"[""unspecified""]",False,False,False,False,False,True,False
33056,"[""unspecified""]",False,False,False,False,False,True,False
37084,"[""unspecified""]",False,False,False,False,False,True,False
42077,"[""unspecified""]",False,True,False,False,False,False,False
42212,"[""unspecified""]",False,True,False,False,False,False,False
42544,"[""unspecified""]",False,True,False,False,False,False,False
42563,"[""unspecified""]",False,False,False,False,False,True,False

In [13]:
inconsistentes = df[
    (df["dietary_profile"].str.contains("unspecified", na=False)) & (
        (df["is_vegan"] == True) |
        (df["is_vegetarian"] == True) |
        (df["is_halal"] == True) |
        (df["is_kosher"] == True) |
        (df["is_nut_free"] == True) |
        (df["is_dairy_free"] == True) |
        (df["is_gluten_free"] == True)
    )
]

print("Total inconsistentes:", len(inconsistentes))

Total inconsistentes: 28

In [ ]:
# no son tantos los inconsistentes

In [14]:


# ==========================================
# FUNCIÓN PARA CREAR DIETARY PROFILE
# ==========================================
def create_dietary_profile(row):

    profile = []

    if row["is_vegan"] == True:
        profile.append("vegan")

    if row["is_vegetarian"] == True:
        profile.append("vegetarian")

    if row["is_halal"] == True:
        profile.append("halal")

    if row["is_kosher"] == True:
        profile.append("kosher")

    if row["is_nut_free"] == True:
        profile.append("nut_free")

    if row["is_dairy_free"] == True:
        profile.append("dairy_free")

    if row["is_gluten_free"] == True:
        profile.append("gluten_free")

    # ==========================================
    # si no tiene ninguna categoría
    # ==========================================
    if len(profile) == 0:
        profile.append("unspecified")

    return json.dumps(profile)


# ==========================================
# CREAR NUEVA COLUMNA
# ==========================================
df["dietary_profile_updated"] = df.apply(
    create_dietary_profile,
    axis=1
)


# ==========================================
# VER RESULTADOS
# ==========================================
df[[
    "dietary_profile",
    "dietary_profile_updated",
    "is_vegan",
    "is_vegetarian",
    "is_dairy_free"
]].head(10)

,dietary_profile,dietary_profile_updated,is_vegan,is_vegetarian,is_dairy_free
0,"[""vegan"", ""gluten_free"", ""nut_free"", ""kosher""]","[""vegan"", ""vegetarian"", ""kosher"", ""nut_free"", ...",True,True,True
1,"[""gluten_free"", ""nut_free""]","[""nut_free"", ""dairy_free"", ""gluten_free""]",False,False,True
2,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]","[""halal"", ""kosher"", ""nut_free"", ""dairy_free"", ...",False,False,True
3,"[""nut_free"", ""halal"", ""kosher""]","[""halal"", ""kosher"", ""nut_free""]",False,False,False
4,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]","[""vegetarian"", ""halal"", ""kosher"", ""nut_free"", ...",False,True,True
5,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]","[""vegetarian"", ""halal"", ""kosher"", ""nut_free"", ...",False,True,False
6,"[""gluten_free"", ""halal"", ""kosher""]","[""halal"", ""kosher"", ""gluten_free""]",False,False,False
7,"[""vegan"", ""nut_free"", ""halal"", ""kosher""]","[""vegan"", ""vegetarian"", ""halal"", ""kosher"", ""nu...",True,True,True
8,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]","[""vegetarian"", ""halal"", ""kosher"", ""nut_free"", ...",False,True,False
9,"[""vegan"", ""gluten_free"", ""nut_free"", ""halal"", ...","[""vegan"", ""vegetarian"", ""halal"", ""kosher"", ""nu...",True,True,True

In [15]:
# quiero ver como se comportan los ingredientes
df[["ingredients", "num_ingredients", "ingredient_text"]].head(7)

,ingredients,num_ingredients,ingredient_text
0,"[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...",9,ketchup beer worcestershire sauce onion powder...
1,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...",5,pound pork belly gochujang soy sauce honey gro...
2,"[""1 ¼ pounds chicken tenders"", ""1 tablespoon o...",3,¼ pounds chicken tenders olive oil everything ...
3,"[""4 chicken cutlets (about 1 pound total)"", ""s...",9,chicken cutlets about pound total salt freshly...
4,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...",5,soy sauce honey sriracha rice vinegar granulat...
5,"[""¼ cup mayonnaise"", ""2 teaspoons crumbled cot...",6,¼ mayonnaise crumbled cotija cheese lime juice...
6,"[""2 tablespoons Thai sweet chili sauce"", ""1 ta...",13,thai sweet chili sauce soy sauce sriracha lime...

In [16]:
# vamos a limpiar los ingredientes para transformar y separar por comas en lugar de tener en raw


# ==========================================
# FUNCIÓN PARA LIMPIAR INGREDIENTES
# ==========================================
def clean_ingredient(text):

    text = text.lower()

    # ==========================================
    # quitar contenido entre paréntesis
    # ejemplo:
    # (14 ounce)
    # (6 ounce)
    # ==========================================
    text = re.sub(r'\([^)]*\)', '', text)

    # ==========================================
    # quitar cantidades al inicio
    # ejemplos:
    # 1
    # 1/2
    # 1 1/2
    # 2.5
    # ¼
    # ½
    # ==========================================
    text = re.sub(
        r'^\s*(\d+\s\d+/\d+|\d+/\d+|\d+(\.\d+)?|[¼½¾⅓⅔⅛⅜⅝⅞]+)\s*',
        '',
        text
    )

    # ==========================================
    # quitar unidades comunes
    # ==========================================
    units = [
        "cup", "cups",
        "tablespoon", "tablespoons",
        "teaspoon", "teaspoons",
        "ounce", "ounces",
        "pound", "pounds",
        "lb", "lbs",
        "can", "cans",
        "container", "containers",
        "package", "packages",
        "strip", "strips",
        "pint", "pints",
        "quart", "quarts",
        "gallon", "gallons",
        "jar", "jars",
        "head", "heads",
        "link", "links",
        "pinch", "pinches"
    ]

    pattern = r'\b(' + '|'.join(units) + r')\b'
    text = re.sub(pattern, '', text)

    # ==========================================
    # quitar fracciones unicode restantes
    # ==========================================
    text = re.sub(r'^[¼½¾⅓⅔⅛⅜⅝⅞]+\s*', '', text)

    # ==========================================
    # reemplazar " and " por coma
    # ==========================================
    text = re.sub(r'\sand\s', ', ', text)

    # ==========================================
    # limpiar espacios extras
    # ==========================================
    text = re.sub(r'\s+', ' ', text)

    # ==========================================
    # limpiar comas extras
    # ==========================================
    text = re.sub(r'\s*,\s*', ', ', text)
    text = re.sub(r',+', ',', text)

    text = text.strip(" ,")

    # ==========================================
    # eliminar strings basura
    # ==========================================
    if len(text) < 3:
        return ""

    bad_endings = [" or", " and"]

    for ending in bad_endings:
        if text.endswith(ending):
            text = text[:-len(ending)].strip()

    return text


# ==========================================
# CREAR COLUMNA PROCESADA
# ==========================================
def process_ingredients(ingredients_json):

    ingredients_list = json.loads(ingredients_json)

    cleaned = [clean_ingredient(i) for i in ingredients_list]

    # eliminar vacíos
    cleaned = [i for i in cleaned if i != ""]

    return ", ".join(cleaned)


df["ingredients_text_processed"] = df["ingredients"].apply(process_ingredients)


listas = df["ingredients_text_processed"].str.split(",")

valores_unicos = set()

for lista in listas:

    ingredientes_limpios = [
        i.strip()
        for i in lista
        if i.strip() != ""
    ]

    valores_unicos.update(ingredientes_limpios)

# ==========================================
# eliminar strings vacíos por seguridad
# ==========================================
valores_unicos.discard("")

# ==========================================
# resultados
# ==========================================
print("Total únicos:", len(valores_unicos))

print(valores_unicos)


df["ingredients_text_processed"] = df["ingredients"].apply(process_ingredients)

Total únicos: 20867

In [17]:
df[["ingredients", "num_ingredients", "ingredient_text", "ingredients_text_processed"]].head(7)

,ingredients,num_ingredients,ingredient_text,ingredients_text_processed
0,"[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...",9,ketchup beer worcestershire sauce onion powder...,"ketchup, beer, worcestershire sauce, onion pow..."
1,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...",5,pound pork belly gochujang soy sauce honey gro...,"pork belly, gochujang, soy sauce, honey, groun..."
2,"[""1 ¼ pounds chicken tenders"", ""1 tablespoon o...",3,¼ pounds chicken tenders olive oil everything ...,"chicken tenders, olive oil, everything bagel s..."
3,"[""4 chicken cutlets (about 1 pound total)"", ""s...",9,chicken cutlets about pound total salt freshly...,"chicken cutlets, salt, freshly ground black pe..."
4,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...",5,soy sauce honey sriracha rice vinegar granulat...,"soy sauce, honey, sriracha, rice vinegar, gran..."
5,"[""¼ cup mayonnaise"", ""2 teaspoons crumbled cot...",6,¼ mayonnaise crumbled cotija cheese lime juice...,"mayonnaise, crumbled cotija cheese, lime juice..."
6,"[""2 tablespoons Thai sweet chili sauce"", ""1 ta...",13,thai sweet chili sauce soy sauce sriracha lime...,"thai sweet chili sauce, soy sauce, sriracha, l..."

In [18]:
# reemplazar "and" por ","
df["ingredients_text_processed"] = (
    df["ingredients_text_processed"]
    .str.replace(r"\sand\s", ", ", regex=True)
)

In [19]:
df[["ingredients", "num_ingredients", "ingredient_text", "ingredients_text_processed"]].head(2)

,ingredients,num_ingredients,ingredient_text,ingredients_text_processed
0,"[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...",9,ketchup beer worcestershire sauce onion powder...,"ketchup, beer, worcestershire sauce, onion pow..."
1,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...",5,pound pork belly gochujang soy sauce honey gro...,"pork belly, gochujang, soy sauce, honey, groun..."

In [20]:
# quiero ver como se comportan los directions
df[["directions", "directions_text", "num_steps", "directions_raw"]].head(7)

,directions,directions_text,num_steps,directions_raw
0,"[""Combine ketchup, beer, Worcestershire sauce,...","combine ketchup, beer, worcestershire sauce, o...",5,"[""Combine ketchup, beer, Worcestershire sauce,..."
1,"[""Preheat an air fryer to 400 degrees F (200 d...",preheat an air fryer to 400 degrees f (200 deg...,4,"[""Preheat an air fryer to 400 degrees F (200 d..."
2,"[""Gather all ingredients. Preheat an air fryer...",gather all ingredients. preheat an air fryer t...,4,"[""Gather all ingredients. Preheat an air fryer..."
3,"[""Preheat an air fryer to 400 degrees F (200 d...",preheat an air fryer to 400 degrees f (200 deg...,9,"[""Preheat an air fryer to 400 degrees F (200 d..."
4,"[""Preheat an air fryer to 400 degrees F (200 d...",preheat an air fryer to 400 degrees f (200 deg...,5,"[""Preheat an air fryer to 400 degrees F (200 d..."
5,"[""Preheat an air fryer to 400 degrees F (200 d...",preheat an air fryer to 400 degrees f (200 deg...,4,"[""Preheat an air fryer to 400 degrees F (200 d..."
6,"[""Combine chili sauce, soy sauce, Sriracha, li...","combine chili sauce, soy sauce, sriracha, lime...",7,"[""Combine chili sauce, soy sauce, Sriracha, li..."

In [21]:
# parece que directions es igual a directions_raw
# se puede usar directions para trabajar modelos
# directions_text para NLP/embeddings
# directions_raw podemos no usarlo

# igual hare una prueba para ver si son lo mismo directions_text y directions
for i in range(3):

    directions_list = json.loads(df.iloc[i]["directions"])
    directions_text = df.iloc[i]["directions_text"]

    # unir la lista en un solo string
    joined = " ".join(directions_list).lower()

    print(f"\nROW {i}")
    print("¿Son iguales?:", joined == directions_text)

ROW 0
¿Son iguales?: True

ROW 1
¿Son iguales?: True

ROW 2
¿Son iguales?: True

In [22]:
# quiero ver como se comportan los ingredientes
df[["ingredients", "num_ingredients", "ingredient_text", "ingredients_canonical"]].head(7)

,ingredients,num_ingredients,ingredient_text,ingredients_canonical
0,"[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...",9,ketchup beer worcestershire sauce onion powder...,"[""ketchup"", ""beer"", ""worcestershire sauce"", ""o..."
1,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...",5,pound pork belly gochujang soy sauce honey gro...,"[""pound pork belly"", ""gochujang"", ""soy sauce"",..."
2,"[""1 ¼ pounds chicken tenders"", ""1 tablespoon o...",3,¼ pounds chicken tenders olive oil everything ...,"[""¼ pounds chicken tenders"", ""olive oil"", ""eve..."
3,"[""4 chicken cutlets (about 1 pound total)"", ""s...",9,chicken cutlets about pound total salt freshly...,"[""chicken cutlets about pound total"", ""salt fr..."
4,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...",5,soy sauce honey sriracha rice vinegar granulat...,"[""soy sauce"", ""honey"", ""sriracha"", ""rice vineg..."
5,"[""¼ cup mayonnaise"", ""2 teaspoons crumbled cot...",6,¼ mayonnaise crumbled cotija cheese lime juice...,"[""¼ mayonnaise"", ""crumbled cotija cheese"", ""li..."
6,"[""2 tablespoons Thai sweet chili sauce"", ""1 ta...",13,thai sweet chili sauce soy sauce sriracha lime...,"[""thai sweet chili sauce"", ""soy sauce"", ""srira..."

In [23]:


df["ingredients_canonical_text"] = df[
    "ingredients_canonical"
].apply(
    lambda x: ", ".join(json.loads(x))
)

df[[
    "ingredients_canonical",
    "ingredients_canonical_text"
]].head()

,ingredients_canonical,ingredients_canonical_text
0,"[""ketchup"", ""beer"", ""worcestershire sauce"", ""o...","ketchup, beer, worcestershire sauce, onion pow..."
1,"[""pound pork belly"", ""gochujang"", ""soy sauce"",...","pound pork belly, gochujang, soy sauce, honey,..."
2,"[""¼ pounds chicken tenders"", ""olive oil"", ""eve...","¼ pounds chicken tenders, olive oil, everythin..."
3,"[""chicken cutlets about pound total"", ""salt fr...","chicken cutlets about pound total, salt freshl..."
4,"[""soy sauce"", ""honey"", ""sriracha"", ""rice vineg...","soy sauce, honey, sriracha, rice vinegar, gran..."

In [ ]:
# lo que hice de ingredients_text_processed en realidad ya estaba en canonical
#ingredients_canonical	usar SÍ
#ingredients_canonical_text	SÍ para NLP

In [24]:
# quiero hacer una radiografia del dataset
# ==========================================
# EXPLORACIÓN GENERAL DE COLUMNAS
# ==========================================

for col in df.columns:

    print("\n" + "="*80)
    print(f"COLUMNA: {col}")

    # tipo de dato
    print(f"\nTipo: {df[col].dtype}")

    # nulls
    print(f"Nulls: {df[col].isnull().sum()}")

    # valores únicos
    try:
        print(f"Valores únicos: {df[col].nunique()}")
    except:
        print("No se pudo calcular únicos")

    # ejemplos
    print("\nEjemplos:")

    try:
        ejemplos = df[col].dropna().sample(
            min(3, len(df[col].dropna())),
            random_state=42
        )

        for i, val in enumerate(ejemplos, 1):

            texto = str(val)

            # cortar textos largos
            if len(texto) > 300:
                texto = texto[:300] + "..."

            print(f"\n[{i}] {texto}")

    except:
        print("No se pudieron mostrar ejemplos")

================================================================================
COLUMNA: recipe_title

Tipo: str
Nulls: 0
Valores únicos: 24971

Ejemplos:

[1] Pound Cake with Lemon Coconut Glaze

[2] Grandpa's Classic Coney Sauce

[3] Air Fryer Baked Potatoes

================================================================================
COLUMNA: category

Tipo: str
Nulls: 0
Valores únicos: 267

Ejemplos:

[1] Cakes

[2] July 4Th

[3] Healthy Recipes

================================================================================
COLUMNA: subcategory

Tipo: str
Nulls: 0
Valores únicos: 1032

Ejemplos:

[1] Coconut Cake

[2] 4Th Of July Side Dishes

[3] Low-Cholesterol Recipes

================================================================================
COLUMNA: description

Tipo: str
Nulls: 0
Valores únicos: 25015

Ejemplos:

[1] Healthier take on pound cake; indulge with no regrets!

[2] Coney sauce is a condiment of ground beef simmered in tangy flavors and served on hot dogs. My grandfather owned a drive-in restaurant back in the 1950s. This is his exact recipe for Coney dogs from back in the day. I make this on special occasions, and it is always hit with friends and family.

[3] A baked potato in the air fryer comes out beautifully crusty on the outside and light and fluffy on the inside, just what a great baked potato should be! Serve them with your favorite toppings, like sour cream, butter, or chives.

================================================================================
COLUMNA: ingredients

Tipo: str
Nulls: 0
Valores únicos: 24971

Ejemplos:

[1] ["1 cup all-purpose flour", "3 tablespoons all-purpose flour", "1 cup white whole wheat flour", "3 tablespoons white whole wheat flour", "2 tablespoons cornstarch", "⅛ teaspoon baking soda", "½ cup soy milk", "½ tablespoon apple cider vinegar", "½ cup coconut oil, at room temperature", "1 ¼ cups whi...

[2] ["2 pounds ground beef", "½ cup chopped onion", "1 ½ cups ketchup", "¼ cup white sugar", "¼ cup white vinegar", "¼ cup prepared yellow mustard", "¾ teaspoon Worcestershire sauce", "¾ teaspoon salt", "½ teaspoon celery seed", "½ teaspoon ground black pepper"]

[3] ["2 large russet potatoes, scrubbed", "1 tablespoon peanut oil", "½ teaspoon coarse sea salt"]

================================================================================
COLUMNA: directions

Tipo: str
Nulls: 0
Valores únicos: 25014

Ejemplos:

[1] ["Preheat the oven to 325 degrees F (165 degrees C). Butter and flour an 8x5-inch loaf pan.", "Sift 1 cup plus 3 tablespoons all-purpose flour, 1 cup plus 3 tablespoons whole wheat flour, cornstarch, and baking soda together into a bowl.", "Mix soy milk and vinegar together in a small bowl. Let stan...

[2] ["Gather the ingredients.", "Place ground beef and onion in a large skillet over medium-high heat. Cook, stirring to crumble, until beef is browned; drain.", "Transfer the beef and onion to a slow cooker and stir in ketchup, sugar, vinegar, and mustard. Season with Worcestershire, salt, celery seed,...

[3] ["Gather all ingredients and preheat an air fryer to 400 degrees F (200 degrees C).", "Brush potatoes with peanut oil, sprinkle with salt, and place them in the air fryer basket.", "Cook potatoes until very tender when pierced with a fork, about 1 hour. Serve and enjoy!"]

================================================================================
COLUMNA: num_ingredients

Tipo: int64
Nulls: 0
Valores únicos: 32

Ejemplos:

[1] 12

[2] 10

[3] 3

================================================================================
COLUMNA: num_steps

Tipo: int64
Nulls: 0
Valores únicos: 20

Ejemplos:

[1] 8

[2] 4

[3] 3

================================================================================
COLUMNA: ingredient_text

Tipo: str
Nulls: 0
Valores únicos: 24962

Ejemplos:

[1] all-purpose flour all-purpose flour white whole wheat flour white whole wheat flour cornstarch ⅛ baking soda ½ soy milk ½ apple cider vinegar ½ coconut oil at room temperature ¼ white sugar eggs ½ pure vanilla extract

[2] pounds ground beef ½ chopped onion ½ ketchup ¼ white sugar ¼ white vinegar ¼ prepared yellow mustard ¾ worcestershire sauce ¾ salt ½ celery seed ½ ground black pepper

[3] large russet potatoes scrubbed peanut oil ½ coarse sea salt

================================================================================
COLUMNA: directions_text

Tipo: str
Nulls: 0
Valores únicos: 25013

Ejemplos:

[1] preheat the oven to 325 degrees f (165 degrees c). butter and flour an 8x5-inch loaf pan. sift 1 cup plus 3 tablespoons all-purpose flour, 1 cup plus 3 tablespoons whole wheat flour, cornstarch, and baking soda together into a bowl. mix soy milk and vinegar together in a small bowl. let stand until ...

[2] gather the ingredients. place ground beef and onion in a large skillet over medium-high heat. cook, stirring to crumble, until beef is browned; drain. transfer the beef and onion to a slow cooker and stir in ketchup, sugar, vinegar, and mustard. season with worcestershire, salt, celery seed, and pep...

[3] gather all ingredients and preheat an air fryer to 400 degrees f (200 degrees c). brush potatoes with peanut oil, sprinkle with salt, and place them in the air fryer basket. cook potatoes until very tender when pierced with a fork, about 1 hour. serve and enjoy!

================================================================================
COLUMNA: combined_text

Tipo: str
Nulls: 0
Valores únicos: 62126

Ejemplos:

[1] pound cake with lemon coconut glaze cakes coconut cake 1 cup all-purpose flour 3 tablespoons all-purpose flour 1 cup white whole wheat flour 3 tablespoons white whole wheat flour 2 tablespoons cornstarch ⅛ teaspoon baking soda ½ cup soy milk ½ tablespoon apple cider vinegar ½ cup coconut oil, at roo...

[2] grandpa's classic coney sauce july 4th 4th of july side dishes 2 pounds ground beef ½ cup chopped onion 1 ½ cups ketchup ¼ cup white sugar ¼ cup white vinegar ¼ cup prepared yellow mustard ¾ teaspoon worcestershire sauce ¾ teaspoon salt ½ teaspoon celery seed ½ teaspoon ground black pepper gather th...

[3] air fryer baked potatoes healthy recipes low-cholesterol recipes 2 large russet potatoes, scrubbed 1 tablespoon peanut oil ½ teaspoon coarse sea salt gather all ingredients and preheat an air fryer to 400 degrees f (200 degrees c). brush potatoes with peanut oil, sprinkle with salt, and place them i...

================================================================================
COLUMNA: ingredients_raw

Tipo: str
Nulls: 0
Valores únicos: 24971

Ejemplos:

[1] ["1 cup all-purpose flour", "3 tablespoons all-purpose flour", "1 cup white whole wheat flour", "3 tablespoons white whole wheat flour", "2 tablespoons cornstarch", "⅛ teaspoon baking soda", "½ cup soy milk", "½ tablespoon apple cider vinegar", "½ cup coconut oil, at room temperature", "1 ¼ cups whi...

[2] ["2 pounds ground beef", "½ cup chopped onion", "1 ½ cups ketchup", "¼ cup white sugar", "¼ cup white vinegar", "¼ cup prepared yellow mustard", "¾ teaspoon Worcestershire sauce", "¾ teaspoon salt", "½ teaspoon celery seed", "½ teaspoon ground black pepper"]

[3] ["2 large russet potatoes, scrubbed", "1 tablespoon peanut oil", "½ teaspoon coarse sea salt"]

================================================================================
COLUMNA: directions_raw

Tipo: str
Nulls: 0
Valores únicos: 25014

Ejemplos:

[1] ["Preheat the oven to 325 degrees F (165 degrees C). Butter and flour an 8x5-inch loaf pan.", "Sift 1 cup plus 3 tablespoons all-purpose flour, 1 cup plus 3 tablespoons whole wheat flour, cornstarch, and baking soda together into a bowl.", "Mix soy milk and vinegar together in a small bowl. Let stan...

[2] ["Gather the ingredients.", "Place ground beef and onion in a large skillet over medium-high heat. Cook, stirring to crumble, until beef is browned; drain.", "Transfer the beef and onion to a slow cooker and stir in ketchup, sugar, vinegar, and mustard. Season with Worcestershire, salt, celery seed,...

[3] ["Gather all ingredients and preheat an air fryer to 400 degrees F (200 degrees C).", "Brush potatoes with peanut oil, sprinkle with salt, and place them in the air fryer basket.", "Cook potatoes until very tender when pierced with a fork, about 1 hour. Serve and enjoy!"]

================================================================================
COLUMNA: ingredients_canonical

Tipo: str
Nulls: 0
Valores únicos: 24962

Ejemplos:

[1] ["all-purpose flour", "all-purpose flour", "white whole wheat flour", "white whole wheat flour", "cornstarch", "⅛ baking soda", "½ soy milk", "½ apple cider vinegar", "½ coconut oil at room temperature", "¼ white sugar", "eggs", "½ pure vanilla extract"]

[2] ["pounds ground beef", "½ chopped onion", "½ ketchup", "¼ white sugar", "¼ white vinegar", "¼ prepared yellow mustard", "¾ worcestershire sauce", "¾ salt", "½ celery seed", "½ ground black pepper"]

[3] ["large russet potatoes scrubbed", "peanut oil", "½ coarse sea salt"]

================================================================================
COLUMNA: cuisine_list

Tipo: str
Nulls: 0
Valores únicos: 2765

Ejemplos:

[1] ["american_region", "asian", "caribbean", "european", "filipino", "french", "greek", "middle eastern region"]

[2] ["american", "american_region", "asian", "european", "filipino", "german"]

[3] ["african", "asian", "thai"]

================================================================================
COLUMNA: course_list

Tipo: str
Nulls: 0
Valores únicos: 1179

Ejemplos:

[1] ["dessert", "bread", "main", "drink"]

[2] ["sauce"]

[3] ["unknown"]

================================================================================
COLUMNA: tastes

Tipo: str
Nulls: 0
Valores únicos: 62

Ejemplos:

[1] ["sweet", "sour", "savory", "umami"]

[2] ["sweet", "sour", "savory", "umami"]

[3] ["savory"]

================================================================================
COLUMNA: primary_taste

Tipo: str
Nulls: 0
Valores únicos: 7

Ejemplos:

[1] sweet

[2] sweet

[3] savory

================================================================================
COLUMNA: secondary_taste

Tipo: str
Nulls: 0
Valores únicos: 6

Ejemplos:

[1] savory

[2] savory

[3] none

================================================================================
COLUMNA: fast_hits

Tipo: int64
Nulls: 0
Valores únicos: 37

Ejemplos:

[1] 12

[2] 3

[3] 2

================================================================================
COLUMNA: slow_hits

Tipo: int64
Nulls: 0
Valores únicos: 20

Ejemplos:

[1] 2

[2] 2

[3] 0

================================================================================
COLUMNA: medium_hits

Tipo: int64
Nulls: 0
Valores únicos: 27

Ejemplos:

[1] 1

[2] 4

[3] 3

================================================================================
COLUMNA: cook_speed

Tipo: str
Nulls: 0
Valores únicos: 3

Ejemplos:

[1] fast

[2] medium

[3] medium

================================================================================
COLUMNA: est_prep_time_min

Tipo: int64
Nulls: 0
Valores únicos: 64

Ejemplos:

[1] 25

[2] 18

[3] 8

================================================================================
COLUMNA: est_cook_time_min

Tipo: int64
Nulls: 0
Valores únicos: 226

Ejemplos:

[1] 53

[2] 56

[3] 24

================================================================================
COLUMNA: difficulty

Tipo: str
Nulls: 0
Valores únicos: 3

Ejemplos:

[1] hard

[2] medium

[3] medium

================================================================================
COLUMNA: is_vegan

Tipo: bool
Nulls: 0
Valores únicos: 2

Ejemplos:

[1] False

[2] False

[3] True

================================================================================
COLUMNA: is_vegetarian

Tipo: bool
Nulls: 0
Valores únicos: 2

Ejemplos:

[1] True

[2] False

[3] True

================================================================================
COLUMNA: is_halal

Tipo: bool
Nulls: 0
Valores únicos: 2

Ejemplos:

[1] True

[2] True

[3] True

================================================================================
COLUMNA: is_kosher

Tipo: bool
Nulls: 0
Valores únicos: 2

Ejemplos:

[1] True

[2] True

[3] True

================================================================================
COLUMNA: is_nut_free

Tipo: bool
Nulls: 0
Valores únicos: 2

Ejemplos:

[1] True

[2] True

[3] False

================================================================================
COLUMNA: is_dairy_free

Tipo: bool
Nulls: 0
Valores únicos: 2

Ejemplos:

[1] False

[2] True

[3] True

================================================================================
COLUMNA: is_gluten_free

Tipo: bool
Nulls: 0
Valores únicos: 2

Ejemplos:

[1] False

[2] True

[3] True

================================================================================
COLUMNA: dietary_profile

Tipo: str
Nulls: 0
Valores únicos: 31

Ejemplos:

[1] ["nut_free", "halal", "kosher"]

[2] ["gluten_free", "nut_free", "halal", "kosher"]

[3] ["vegan", "gluten_free", "halal", "kosher"]

================================================================================
COLUMNA: healthiness_score

Tipo: int64
Nulls: 0
Valores únicos: 40

Ejemplos:

[1] 58

[2] 72

[3] 64

================================================================================
COLUMNA: health_flags

Tipo: str
Nulls: 0
Valores únicos: 57

Ejemplos:

[1] ["plant_based", "whole_grains", "sugary", "fried"]

[2] ["plant_based", "sugary"]

[3] ["fried"]

================================================================================
COLUMNA: main_ingredient

Tipo: str
Nulls: 0
Valores únicos: 6

Ejemplos:

[1] egg_dairy

[2] red_meat

[3] unknown

================================================================================
COLUMNA: health_level

Tipo: str
Nulls: 0
Valores únicos: 3

Ejemplos:

[1] moderate

[2] moderate

[3] moderate

================================================================================
COLUMNA: dietary_profile_updated

Tipo: str
Nulls: 0
Valores únicos: 77

Ejemplos:

[1] ["vegetarian", "halal", "kosher", "nut_free"]

[2] ["halal", "kosher", "nut_free", "dairy_free", "gluten_free"]

[3] ["vegan", "vegetarian", "halal", "kosher", "dairy_free", "gluten_free"]

================================================================================
COLUMNA: ingredients_text_processed

Tipo: str
Nulls: 0
Valores únicos: 24934

Ejemplos:

[1] all-purpose flour, all-purpose flour, white whole wheat flour, white whole wheat flour, cornstarch, baking soda, soy milk, apple cider vinegar, coconut oil, at room temperature, white sugar, eggs, pure vanilla extract

[2] ground beef, chopped onion, ketchup, white sugar, white vinegar, prepared yellow mustard, worcestershire sauce, salt, celery seed, ground black pepper

[3] large russet potatoes, scrubbed, peanut oil, coarse sea salt

================================================================================
COLUMNA: ingredients_canonical_text

Tipo: str
Nulls: 0
Valores únicos: 24962

Ejemplos:

[1] all-purpose flour, all-purpose flour, white whole wheat flour, white whole wheat flour, cornstarch, ⅛ baking soda, ½ soy milk, ½ apple cider vinegar, ½ coconut oil at room temperature, ¼ white sugar, eggs, ½ pure vanilla extract

[2] pounds ground beef, ½ chopped onion, ½ ketchup, ¼ white sugar, ¼ white vinegar, ¼ prepared yellow mustard, ¾ worcestershire sauce, ¾ salt, ½ celery seed, ½ ground black pepper

[3] large russet potatoes scrubbed, peanut oil, ½ coarse sea salt

COLUMNAS RAW VS PROCESADAS
| Tipo            | Ejemplo                              |
| --------------- | ------------------------------------ |
| raw/original    | `ingredients_raw`, `directions_raw`  |
| procesado       | `ingredient_text`, `directions_text` |
| canonical       | `ingredients_canonical`              |
| concatenado NLP | `combined_text`                      |

INGREDIENTS CANONICAL NO ES COMO MI INGREDIENTS PROCESSED, ES MEJOR LO QUE HICE YO, YEIH.

METADATA BÁSICA

| Columna      |
| ------------ |
| recipe_title |
| category     |
| subcategory  |
| description  |

INGREDIENTES
| Columna                    | Estado                         |
| -------------------------- | ------------------------------ |
| ingredients                | original                       |
| ingredients_raw            | redundante                     |
| ingredient_text            | mala concatenación             |
| ingredients_canonical      | semi-limpio                    |
| ingredients_text_processed | probablemente tu mejor versión |


INSTRUCCIONES
| Columna         |
| --------------- |
| directions      |
| directions_raw  |
| directions_text |
| num_steps       |


ETIQUETAS CULINARIAS
| Columna         |
| --------------- |
| cuisine_list    |
| course_list     |
| tastes          |
| primary_taste   |
| secondary_taste |


TIEMPO Y DIFICULTAD
| Columna           |
| ----------------- |
| fast_hits         |
| medium_hits       |
| slow_hits         |
| cook_speed        |
| est_prep_time_min |
| est_cook_time_min |
| difficulty        |


SALUD Y DIETA
| Columna                 |
| ----------------------- |
| is_vegan                |
| is_vegetarian           |
| is_halal                |
| is_kosher               |
| is_nut_free             |
| is_dairy_free           |
| is_gluten_free          |
| dietary_profile         |
| dietary_profile_updated |
| healthiness_score       |
| health_flags            |
| health_level            |

CUALES CONSERVAMOS?

LA PRIMERA OPCIÓN PODRÍA SER
| Mantener                   | Motivo             |
| -------------------------- | ------------------ |
| recipe_title               | título             |
| category                   | categoría          |
| subcategory                | subcategoría       |
| description                | descripción        |
| ingredients_text_processed | mejor ingredientes |
| directions_text            | instrucciones NLP  |
| cuisine_list               | cocina             |
| course_list                | tipo de platillo   |
| tastes                     | sabores            |
| cook_speed                 | velocidad          |
| est_prep_time_min          | tiempo             |
| est_cook_time_min          | tiempo             |
| difficulty                 | dificultad         |
| dietary_profile_updated    | mejor profile      |
| healthiness_score          | score              |
| health_flags               | flags              |
| main_ingredient            | proteína principal |
| health_level               | nivel salud        |


PODEMOS QUITAR LAS REDUNDANTES
| Quitar                                      |
| ------------------------------------------- |
| ingredients_raw                             |
| directions_raw                              |
| ingredient_text                             |
| ingredients_canonical                       |
| combined_text (tal vez regenerarlo después) |
| dietary_profile original                    |

In [ ]:
import json

# ==========================================
# FUNCIÓN PARA EXTRAER VALORES ÚNICOS
# DE COLUMNAS JSON TIPO LISTA
# ==========================================
def get_unique_values(column_name):

    valores_unicos = set()

    for item in df[column_name]:

        try:
            lista = json.loads(item)

            for valor in lista:

                valor = str(valor).strip().lower()

                if valor != "":
                    valores_unicos.add(valor)

        except:
            pass

    return sorted(valores_unicos)


# ==========================================
# COLUMNAS JSON/LISTA A ANALIZAR
# ==========================================
json_columns = [
    "ingredients",
    "directions",
    "ingredients_raw",
    "directions_raw",
    "ingredients_canonical",
    "cuisine_list",
    "course_list",
    "tastes",
    "dietary_profile",
    "dietary_profile_updated",
    "health_flags"
]


# ==========================================
# ANALIZAR TODAS LAS COLUMNAS
# ==========================================
for col in json_columns:

    print("\n" + "="*80)
    print(f"COLUMNA: {col}")

    valores = get_unique_values(col)

    print(f"\nTotal valores únicos: {len(valores)}")

    print("\nPrimeros 10 valores:")
    print(valores[:10])

================================================================================
COLUMNA: ingredients

Total valores únicos: 66849

Primeros 10 valores:
['( (', '(1/4 ounce) active dry yeast', '(15-ounce) black beans,', '(21-ounce) apple pie fruit filling or topping (such as lucky leaf', '(32-ounce) package mashed potatoes', '(8-ounce) sharp cheddar cheese', '.23999999463558 cup chopped cilantro', '.3 cup dark rum', '.79100000858307 cup butter', '1']

================================================================================
COLUMNA: directions

Total valores únicos: 97517

Primeros 10 valores:
['(if using a pan, press sandwich down with a pan lid. cook sandwiches about 3 to 4 minutes on each side or until bread is toasted.)', '(use a funnel that has a 2-inch opening, to layer nicely in jar.) with wire whisk, mix flour, baking powder, and baking soda. pour into jar, pack down level with heavy object.', '*gingered dressing: whisk together 1/4 cup reduced sodium soy sauce, 1/4 cup rice vinegar, 1-inch piece peeled fresh ginger, grated, 2 tablespoons chopped fresh cilantro, 1 tablespoon sesame oil and 2 teaspoons chile paste with garlic until well blended. makes about 2/3 cup.', '[at this point, the dough can be refrigerated: cover dough with greased plastic wrap and refrigerate overnight. the next morning, let pastries come to room temperature for about half an hour before baking as directed in step 7.]', "a drop of batter should sizzle as it hits the oil, indicating it's ready. working in batches, spoon a scant 1/4 cup of batter into the hot oil, and using a spoon, spread slightly into circles. fry until golden brown on both sides, about 3 minutes total. remove from pan to a wire rack set over paper towels and immediately sprinkle with salt to taste.", 'a few minutes before the timer goes off, stir together brown sugar and vinegar in a small saucepan and boil for 1 minute. remove loaves from the oven and pour brown sugar mixture over. return loaves to the oven; baste frequently with the pan juices until browned and cooked through, 30 to 45 minutes more.', 'about 1 1/2 hours before serving time, heat water with reserved pork trimmings in a large saucepan over low heat and simmer to make broth, about 45 minutes. strain broth, discard trimmings, and pour remaining can of beer and kraut juice into the simmering broth. bring the broth to a boil.', 'about 1 hour before serving, heat cream and corn syrup in a small saucepan over medium just to a simmer. place semisweet chocolate chips in a small heatproof bowl; pour cream mixture over chocolate chips and let stand 1 minute. whisk gently until smooth. cool slightly, about 15 minutes.', 'about 1 hour before serving, remove the casserole from the refrigerator, and take off the plastic wrap. preheat oven to 300 degrees f (150 degrees c).', 'about 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. stir cream cheese mixture back into the chili.']

================================================================================
COLUMNA: ingredients_raw

Total valores únicos: 66849

Primeros 10 valores:
['( (', '(1/4 ounce) active dry yeast', '(15-ounce) black beans,', '(21-ounce) apple pie fruit filling or topping (such as lucky leaf', '(32-ounce) package mashed potatoes', '(8-ounce) sharp cheddar cheese', '.23999999463558 cup chopped cilantro', '.3 cup dark rum', '.79100000858307 cup butter', '1']

================================================================================
COLUMNA: directions_raw

Total valores únicos: 97517

Primeros 10 valores:
['(if using a pan, press sandwich down with a pan lid. cook sandwiches about 3 to 4 minutes on each side or until bread is toasted.)', '(use a funnel that has a 2-inch opening, to layer nicely in jar.) with wire whisk, mix flour, baking powder, and baking soda. pour into jar, pack down level with heavy object.', '*gingered dressing: whisk together 1/4 cup reduced sodium soy sauce, 1/4 cup rice vinegar, 1-inch piece peeled fresh ginger, grated, 2 tablespoons chopped fresh cilantro, 1 tablespoon sesame oil and 2 teaspoons chile paste with garlic until well blended. makes about 2/3 cup.', '[at this point, the dough can be refrigerated: cover dough with greased plastic wrap and refrigerate overnight. the next morning, let pastries come to room temperature for about half an hour before baking as directed in step 7.]', "a drop of batter should sizzle as it hits the oil, indicating it's ready. working in batches, spoon a scant 1/4 cup of batter into the hot oil, and using a spoon, spread slightly into circles. fry until golden brown on both sides, about 3 minutes total. remove from pan to a wire rack set over paper towels and immediately sprinkle with salt to taste.", 'a few minutes before the timer goes off, stir together brown sugar and vinegar in a small saucepan and boil for 1 minute. remove loaves from the oven and pour brown sugar mixture over. return loaves to the oven; baste frequently with the pan juices until browned and cooked through, 30 to 45 minutes more.', 'about 1 1/2 hours before serving time, heat water with reserved pork trimmings in a large saucepan over low heat and simmer to make broth, about 45 minutes. strain broth, discard trimmings, and pour remaining can of beer and kraut juice into the simmering broth. bring the broth to a boil.', 'about 1 hour before serving, heat cream and corn syrup in a small saucepan over medium just to a simmer. place semisweet chocolate chips in a small heatproof bowl; pour cream mixture over chocolate chips and let stand 1 minute. whisk gently until smooth. cool slightly, about 15 minutes.', 'about 1 hour before serving, remove the casserole from the refrigerator, and take off the plastic wrap. preheat oven to 300 degrees f (150 degrees c).', 'about 1/2 hour before serving, place cream cheese into a bowl and stir in about 1 tablespoon of the chili liquid until thoroughly combined. continue stirring in chili broth, a tablespoon at a time, until the cream cheese is almost a liquid. stir cream cheese mixture back into the chili.']

================================================================================
COLUMNA: ingredients_canonical

Total valores únicos: 46882

Primeros 10 valores:
['- -inch flour tortillas', '- -inch hoagie rolls', '- -ounce package frozen cauliflower tots', '- -ounce skinless boneless chicken breasts', '- -ounces boneless skinless chicken breasts halved horizontally', '- black beans', '- bottle vodka', '- lemon juice', '- ounce bag corn tortilla chips', '- ounce bag tortilla chips']

================================================================================
COLUMNA: cuisine_list

Total valores únicos: 27

Primeros 10 valores:
['african', 'american', 'american_region', 'asian', 'british', 'caribbean', 'chinese', 'european', 'filipino', 'french']

================================================================================
COLUMNA: course_list

Total valores únicos: 11

Primeros 10 valores:
['appetizer', 'bread', 'breakfast', 'dessert', 'drink', 'main', 'sauce', 'side', 'snack', 'soup']

================================================================================
COLUMNA: tastes

Total valores únicos: 7

Primeros 10 valores:
['bitter', 'neutral', 'savory', 'sour', 'spicy', 'sweet', 'umami']

================================================================================
COLUMNA: dietary_profile

Total valores únicos: 6

Primeros 10 valores:
['gluten_free', 'halal', 'kosher', 'nut_free', 'unspecified', 'vegan']

================================================================================
COLUMNA: dietary_profile_updated

Total valores únicos: 8

Primeros 10 valores:
['dairy_free', 'gluten_free', 'halal', 'kosher', 'nut_free', 'unspecified', 'vegan', 'vegetarian']

================================================================================
COLUMNA: health_flags

Total valores únicos: 7

Primeros 10 valores:
['fried', 'healthy_fats', 'neutral', 'plant_based', 'processed_meat', 'sugary', 'whole_grains']

In [25]:
# ==========================================
# NUEVO DATAFRAME LIMPIO
# ==========================================

columnas_finales = [

    # ======================================
    # METADATA BÁSICA
    # ======================================
    "recipe_title",
    "category",
    "subcategory",
    "description",

    # ======================================
    # INGREDIENTES E INSTRUCCIONES
    # ======================================
    "ingredients",
    "ingredients_text_processed",
    "directions",
    "directions_text",
    "num_ingredients",
    "num_steps",

    # ======================================
    # CLASIFICACIONES CULINARIAS
    # ======================================
    "cuisine_list",
    "course_list",
    "tastes",
    "primary_taste",
    "secondary_taste",

    # ======================================
    # TIEMPOS Y DIFICULTAD
    # ======================================
    "fast_hits",
    "medium_hits",
    "slow_hits",
    "cook_speed",
    "est_prep_time_min",
    "est_cook_time_min",
    "difficulty",

    # ======================================
    # DIETARY / HEALTH
    # ======================================
    "is_vegan",
    "is_vegetarian",
    "is_halal",
    "is_kosher",
    "is_nut_free",
    "is_dairy_free",
    "is_gluten_free",

    "dietary_profile_updated",

    "healthiness_score",
    "health_flags",
    "health_level",

    # ======================================
    # INGREDIENTE PRINCIPAL
    # ======================================
    "main_ingredient"
]

# ==========================================
# CREAR DATAFRAME LIMPIO
# ==========================================
df_clean = df[columnas_finales].copy()


# ==========================================
# INFO GENERAL
# ==========================================
print("Shape original:", df.shape)
print("Shape limpio:", df_clean.shape)

print("\nColumnas finales:\n")
print(df_clean.columns.tolist())

Shape original: (62126, 41)
Shape limpio: (62126, 34)

Columnas finales:

['recipe_title', 'category', 'subcategory', 'description', 'ingredients', 'ingredients_text_processed', 'directions', 'directions_text', 'num_ingredients', 'num_steps', 'cuisine_list', 'course_list', 'tastes', 'primary_taste', 'secondary_taste', 'fast_hits', 'medium_hits', 'slow_hits', 'cook_speed', 'est_prep_time_min', 'est_cook_time_min', 'difficulty', 'is_vegan', 'is_vegetarian', 'is_halal', 'is_kosher', 'is_nut_free', 'is_dairy_free', 'is_gluten_free', 'dietary_profile_updated', 'healthiness_score', 'health_flags', 'health_level', 'main_ingredient']

# analizando el app.py que me mandó Mario

EL APP.PY TIENE

| Campo fake   | Dataset equivalente  |
| ------------ | -------------------- |
| titulo       | recipe_title         |
| ingredientes | ingredients          |
| pasos        | directions           |
| prep_time    | est_prep_time_min    |
| cook_time    | est_cook_time_min    |
| difficulty   | difficulty           |
| dieta        | dietary_profile      |
| porciones    | no existe en dataset |

Porciones no podemos usarlo.

ESTO ES LO QUE ESTABA EN EL FRONTEND  
| Dataset column    | UI feature   |
| ----------------- | ------------ |
| dietary_profile   | badges       |
| difficulty        | dificultad   |
| est_prep_time_min | prep         |
| est_cook_time_min | cook         |
| directions        | pasos        |
| ingredients       | ingredientes |

INPUT
"quiero algo rápido, vegetariano y con arroz"

EMBEDDING DEL PROMPT

EMBEDDINGS DEL DATASET
recipe_title
ingredients_text_processed
directions_text
dietary_profile_updated
tastes
cook_speed




BUSQUEDA DE DATA SIMILAR

-------------------------------------
cosine similarity

↓

Recuperar top recetas

↓

GPT-2 reformula/genera salida bonita

-------------------------------------

# En cuanto al data set, hay que crear una columna para el embedding
## por ejemplo embeding_text


EJEMPLO

Title: Air Fryer Potatoes

Ingredients:
potatoes, olive oil, garlic powder

Diet:
vegetarian, gluten_free

Taste:
savory

Cook speed:
fast

Directions:
preheat air fryer...

# HAY QUE USAR INFORMACIÓN RELEVANTE
podríamos eliminar
- fast_hits
- medium_hits
- slow_hits
- num_steps

Y LO QUE PODRÍAMOS USAR
| Columna                    | Sí/No   |
| -------------------------- | ------- |
| recipe_title               | Sí      |
| ingredients_text_processed | Sí      |
| directions_text            | Sí      |
| dietary_profile_updated    | Sí      |
| tastes                     | Sí      |
| cook_speed                 | Sí      |
| difficulty                 | tal vez |
| cuisine_list               | sí      |
| course_list                | sí      |

In [26]:

# queremos dificultad o no?
# vamos a hacer las dos opciones



# ==========================================
# FUNCIÓN AUXILIAR
# convierte listas JSON a texto
# ==========================================
def json_list_to_text(value):

    try:
        lista = json.loads(value)
        return ", ".join(lista)

    except:
        return str(value)


# ==========================================
# OPCIÓN 1
# CON DIFICULTAD
# ==========================================
def build_embedding_text_with_difficulty(row):

    cuisines = json_list_to_text(row["cuisine_list"])
    courses = json_list_to_text(row["course_list"])
    tastes = json_list_to_text(row["tastes"])
    dietary = json_list_to_text(row["dietary_profile_updated"])
    health_flags = json_list_to_text(row["health_flags"])

    text = f"""
    Title: {row['recipe_title']}

    Category: {row['category']}
    Subcategory: {row['subcategory']}

    Description:
    {row['description']}

    Ingredients:
    {row['ingredients_text_processed']}

    Directions:
    {row['directions_text']}

    Cuisine:
    {cuisines}

    Course:
    {courses}

    Tastes:
    {tastes}

    Dietary profile:
    {dietary}

    Health flags:
    {health_flags}

    Main ingredient:
    {row['main_ingredient']}

    Cook speed:
    {row['cook_speed']}

    Difficulty:
    {row['difficulty']}
    """

    return " ".join(text.split())


# ==========================================
# OPCIÓN 2
# SIN DIFICULTAD
# ==========================================
def build_embedding_text_without_difficulty(row):

    cuisines = json_list_to_text(row["cuisine_list"])
    courses = json_list_to_text(row["course_list"])
    tastes = json_list_to_text(row["tastes"])
    dietary = json_list_to_text(row["dietary_profile_updated"])
    health_flags = json_list_to_text(row["health_flags"])

    text = f"""
    Title: {row['recipe_title']}

    Category: {row['category']}
    Subcategory: {row['subcategory']}

    Description:
    {row['description']}

    Ingredients:
    {row['ingredients_text_processed']}

    Directions:
    {row['directions_text']}

    Cuisine:
    {cuisines}

    Course:
    {courses}

    Tastes:
    {tastes}

    Dietary profile:
    {dietary}

    Health flags:
    {health_flags}

    Main ingredient:
    {row['main_ingredient']}

    Cook speed:
    {row['cook_speed']}
    """

    return " ".join(text.split())


# ==========================================
# CREAR COLUMNAS
# ==========================================
df_clean["embedding_text_with_difficulty"] = df_clean.apply(
    build_embedding_text_with_difficulty,
    axis=1
)

df_clean["embedding_text_without_difficulty"] = df_clean.apply(
    build_embedding_text_without_difficulty,
    axis=1
)


# ==========================================
# VER EJEMPLOS
# ==========================================
print("\n========== WITH DIFFICULTY ==========\n")
print(df_clean["embedding_text_with_difficulty"].iloc[0])

print("\n\n========== WITHOUT DIFFICULTY ==========\n")
print(df_clean["embedding_text_without_difficulty"].iloc[0])

========== WITH DIFFICULTY ==========

Title: Air Fryer Potato Slices with Dipping Sauce Category: Air Fryer Recipes Subcategory: Air Fryer Recipes Description: These air fryer potato slices, served with a beer ketchup dipping sauce, are a tasty finger food somewhere between a French fry and a potato chip. Do take the time to make the dipping sauce—it's worth it. Ingredients: ketchup, beer, worcestershire sauce, onion powder, cayenne, baking potatoes, olive oil cooking spray, garlic powder, salt, freshly ground black pepper Directions: combine ketchup, beer, worcestershire sauce, onion powder, and cayenne in a small saucepan. bring to a boil, then reduce heat, and simmer for 3 to 5 minutes. remove from heat, and cool. cover and store in the refrigerator until ready to use. preheat the air fryer to 400 degrees f (200 degrees c). spray the basket with cooking spray or line with a disposable parchment liner. slice potatoes 1/4-inch thick (use a mandoline if you have one), and place in a bowl. spray potatoes with olive oil spray, and sprinkle with garlic powder, salt and pepper. give the potatoes a good stir. place potatoes in a single layer in the air fryer, and cook, shaking occasionally, until they start to crisp up a bit and turn golden brown, 14 to 17 minutes. cooking times can vary depending on the brand and size of the fryer, and you may have to cook in batches. remove from the fryer, and serve with beer ketchup dipping sauce. Cuisine: american, american_region, asian, european, greek, korean, mediterranean, middle eastern region Course: sauce Tastes: spicy, bitter, savory Dietary profile: vegan, vegetarian, kosher, nut_free, dairy_free, gluten_free Health flags: plant_based, healthy_fats, fried Main ingredient: unknown Cook speed: medium Difficulty: hard


========== WITHOUT DIFFICULTY ==========

Title: Air Fryer Potato Slices with Dipping Sauce Category: Air Fryer Recipes Subcategory: Air Fryer Recipes Description: These air fryer potato slices, served with a beer ketchup dipping sauce, are a tasty finger food somewhere between a French fry and a potato chip. Do take the time to make the dipping sauce—it's worth it. Ingredients: ketchup, beer, worcestershire sauce, onion powder, cayenne, baking potatoes, olive oil cooking spray, garlic powder, salt, freshly ground black pepper Directions: combine ketchup, beer, worcestershire sauce, onion powder, and cayenne in a small saucepan. bring to a boil, then reduce heat, and simmer for 3 to 5 minutes. remove from heat, and cool. cover and store in the refrigerator until ready to use. preheat the air fryer to 400 degrees f (200 degrees c). spray the basket with cooking spray or line with a disposable parchment liner. slice potatoes 1/4-inch thick (use a mandoline if you have one), and place in a bowl. spray potatoes with olive oil spray, and sprinkle with garlic powder, salt and pepper. give the potatoes a good stir. place potatoes in a single layer in the air fryer, and cook, shaking occasionally, until they start to crisp up a bit and turn golden brown, 14 to 17 minutes. cooking times can vary depending on the brand and size of the fryer, and you may have to cook in batches. remove from the fryer, and serve with beer ketchup dipping sauce. Cuisine: american, american_region, asian, european, greek, korean, mediterranean, middle eastern region Course: sauce Tastes: spicy, bitter, savory Dietary profile: vegan, vegetarian, kosher, nut_free, dairy_free, gluten_free Health flags: plant_based, healthy_fats, fried Main ingredient: unknown Cook speed: medium

Ya hice una limpieza y análisis bastante completo del dataset.

Primero revisé todas las columnas para entender cuáles eran útiles, cuáles eran raw/redundantes y cómo estaba estructurada la info.

Después limpié ingredientes y armé una nueva columna (`ingredients_text_processed`) para dejar los ingredientes más limpios y útiles para NLP/embeddings, quitando cantidades, unidades, ruido, etc.

También encontré que el `dietary_profile` estaba incompleto (no incluía vegetarian ni dairy_free aunque sí existían los booleanos), así que hice una nueva columna `dietary_profile_updated` usando todos los flags reales (`is_vegan`, `is_vegetarian`, etc.) para que quede consistente.

Luego hice un dataframe limpio (`df_clean`) quitando columnas redundantes o que realmente no aportaban mucho.

Y al final armé dos columnas especiales para embeddings:

* `embedding_text_with_difficulty`
* `embedding_text_without_difficulty`

Las dos juntan toda la info importante de la receta en un solo texto:
título, ingredientes, pasos, dieta, tastes, cuisine, cook speed, etc.

La única diferencia es que una incluye dificultad y la otra no, para que podamos probar cuál funciona mejor.

Con eso ya se pueden empezar a hacer embeddings, similarity search o conectar GPT-2/Sentence Transformers, más o menos como el demo/dummy que vimos con Mario donde escribes algo tipo “quiero algo rápido y vegetariano” y el sistema busca recetas parecidas semánticamente.